name: Build & Deploy Widget

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install & build (if applicable)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

      # Deploy step using connection string
      - name: Deploy to Azure Blob Storage using Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --source './dist' \
              --destination '$web' \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --overwrite true
